### ISSUE TITLE
Question regarding the "Computing the intensity" portion of the The Basics

### ISSUE THREAD

**Issue by psaxena2** [psaxena2/github-slideshow#2]
I'm going through the basics tutorial for starry (which I'm really excited to use for a number of different projects!) and am running into an issue I was hoping you had some advice on.  

When I try to plot the intensity of the Earth along the equator, i get the following error (this is all from the python command line): 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2761, in plot
>     return gca().plot(
>   File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1646, in plot
>     lines = [*self._get_lines(*args, data=data, **kwargs)]
>   File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 216, in __call__
>     yield from self._plot_args(this, kwargs)
>   File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 332, in _plot_args
>     y = _check_1d(tup[-1])
>   File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 1325, in _check_1d
>     if not hasattr(x, 'shape') or len(x.shape) < 1:
> TypeError: object of type 'TensorVariable' has no len()

I saw the Theano tutorial addresses this with the following: _Python requires that __len__ returns an integer, yet it cannot be done as Theano’s variables are symbolic. However, var.shape[0] can be used as a workaround._

I was wondering whether that means I need edit the corresponding line in the file where the issue is arising and whether you have a recommendation on how to do that.  Sorry if this is a simple question or something on my end!

Thanks
Prabal

**Comment by psaxena2** [comment]
> I'm going through the basics tutorial for starry (which I'm really excited to use for a number of different projects!) and am running into an issue I was hoping you had some advice on.
> 
> When I try to plot the intensity of the Earth along the equator, i get the following error (this is all from the python command line):
> 
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2761, in plot
> > return gca().plot(
> > File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1646, in plot
> > lines = [*self._get_lines(*args, data=data, **kwargs)]
> > File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 216, in **call**
> > yield from self._plot_args(this, kwargs)
> > File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 332, in _plot_args
> > y = _check_1d(tup[-1])
> > File "/Users/psaxena1/Desktop/ExoVolcanology/Starry/lib/python3.8/site-packages/matplotlib/cbook/**init**.py", line 1325, in _check_1d
> > if not hasattr(x, 'shape') or len(x.shape) < 1:
> > TypeError: object of type 'TensorVariable' has no len()
> 
> I saw the Theano tutorial addresses this with the following: _Python requires that **len** returns an integer, yet it cannot be done as Theano’s variables are symbolic. However, var.shape[0] can be used as a workaround._
> 
> I was wondering whether that means I need edit the corresponding line in the file where the issue is arising and whether you have a recommendation on how to do that. Sorry if this is a simple question or something on my end!
> 
> Thanks
> Prabal

Closing issue as an example of how to do so.
